export const service = [
  {
    id: 1,
    img: "../assets/cake.png",
    title: "Birthdays",
    category: "birthdays",
    quote: "A Party without Cake is just a Meeting",
    price: 99,
    rating: 4.2,
    deal: 234,
  },
  {
    id: 2,
    img: "../assets/cake.png",
    title: "Anniversaries",
    category: "anniversaries",
    quote: "Live Life in full Bloom",
    price: 29,
    rating: 4.9,
    deal: 27,
  },
  {
    id: 3,
    img: "https://www.fluentin3months.com/wp-content/uploads/2021/09/language-meetup.jpg",
    title: "MEETUPS",
    category: "meetups",
    quote: "Love the Giver more than the Gifts",
    price: 49,
    rating: 4.7,
    deal: 127,
  },
];

export const types = [
  {
    id: 1,
    img: "../assets/cake.png",
    title: "Cakes",
    category: "cakes",
    quote: "A Party without Cake is just a Meeting",
    price: 99,
    rating: 4.2,
    deal: 234,
  },
  {
    id: 2,
    img: "../assets/cake.png",
    title: "Flowers",
    category: "flowers",
    quote: "Live Life in full Bloom",
    price: 29,
    rating: 4.9,
    deal: 27,
  },
  {
    id: 3,
    img: "https://www.fluentin3months.com/wp-content/uploads/2021/09/language-meetup.jpg",
    title: "Gifts",
    category: "gifts",
    quote: "Love the Giver more than the Gifts",
    price: 49,
    rating: 4.7,
    deal: 127,
  },
];
